name: Deploy Sustaflex Landing

on:
  push:
    branches: [ main, master ] # Ikkala branchga ham reaksiya beradi

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64] # Aniq label yozdik
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: Copy to Web Folder
        run: |
          rm -rf /home/user/Projects/Euphoria/lands/sustaflex-landing.uz/*
          cp -r out/* /home/user/Projects/Euphoria/lands/sustaflex-landing.uz/